environment:
  matrix:
    - node_version: "6"
    - node_version: "4"



build_script:
  - npm run build
  - npm run build
  - npm run build-win-installer

test_script:
  - node --version
  - npm run test-only -- --maxWorkers 3

artifacts:
  - path: artifacts/*.msi
    name: Installer



