# Setup
title:        Bit docs
tagline:      distributed code component manager
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       bit
  url:        http://teambit.github.com 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown