# Setup
title:        Bit
tagline:      distributed code component manager
baseurl:      "https://github.com/teambit/bit"
paginate:     1

# About/contact
author:
  name:       Rany
  url:        https://teambit.github.io/bit/

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown